language: csharp
solution: MyExpenses.sln

notifications:
 email:
  on_success: change
  on_failure: change

dist: bionic
mono: none
dotnet: 2.2

install:
 - dotnet tool install --global dotnet-sonarscanner

before_script:
 - dotnet restore
 - export PATH="$PATH:$HOME/.dotnet/tools"

script:
 - dotnet build || travis_terminate 1;
 - dotnet test || travis_terminate 1;

after_success:
 - dotnet sonarscanner begin /k:$SONARCLOUD_KEY /o:$SONARCLOUD_ORG /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login=$SONARCLOUD_TOKEN /d:sonar.cs.opencover.reportsPaths="tests\**\coverage.opencover.xml" /d:sonar.branch.name=$TRAVIS_BRANCH
 - dotnet build --no-incremental
 - dotnet test /p:Exclude="$TEST_EXCLUDE" /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
 - dotnet sonarscanner end /d:sonar.login=$SONARCLOUD_TOKEN