language: csharp
solution: MyExpenses.sln

notifications:
    email:
        on_success: change
        on_failure: change

dist: bionic
mono: none
dotnet: 2.2

install:
    - dotnet tool install --global dotnet-sonarscanner

before_script:
    - dotnet restore
    - export PATH="$PATH:$HOME/.dotnet/tools"

jobs:
    include:
        - stage: "Build and Test"
            script:
                - dotnet build
                - dotnet test
        - stage: "Build and Test 2"
            script:
                - dotnet build --no-incremental
                - dotnet test
        #- stage: "Publish Results"
        #    script:
        #        - dotnet sonarscanner begin /k:$SONARCLOUD_PROJECT /o:"lfmachadodasilva-github" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login=$SONARCLOUD_TOKEN /d:sonar.cs.opencover.reportsPaths="tests\**\coverage.opencover.xml" /d:sonar.branch.name=$TRAVIS_BRANCH
        #        - dotnet build --no-incremental
        #        - dotnet test /p:Exclude="$TEST_EXCLUDE" /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
        #        - dotnet sonarscanner end /d:sonar.login=$SONARCLOUD_TOKEN