language: csharp
solution: MyExpenses.sln

notifications:
  email:
    on_success: change
    on_failure: change

dist: bionic
mono: none
dotnet: 2.2

install:
 - git config --global core.autocrlf true
 - dotnet tool install --global dotnet-sonarscanner
 - dotnet tool install --global coverlet.console

before_script:
 - dotnet restore

script:
 - dotnet-sonarscanner begin /k:$SONARCLOUD_PROJEC /d:sonar.organization=$SONARCLOUD_ORGANIZATION /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login=$SONARCLOUD_TOKEN /d:sonar.cs.opencover.reportsPaths="tests\**\coverage.opencover.xml" /d:sonar.branch.name=$APPVEYOR_REPO_BRANCH
 - dotnet build || travis_terminate 1;
 - dotnet test /p:Exclude="$TEST_EXCLUDE" /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
 - dotnet-sonarscanner end /d:sonar.login=$SONARCLOUD_TOKEN