language: csharp
solution: MyExpenses.sln

notifications:
  email:
    on_success: change
    on_failure: change

dist: bionic
mono: none
dotnet: 2.2

script:
  - dotnet restore
  - dotnet build /p:Configuration=Release || travis_terminate 1;
  - dotnet test || travis_terminate 1;