language: csharp
solution: MyExpenses.sln

notifications:
  email:
    on_success: change
    on_failure: change

dist: bionic
mono: none
dotnet: 2.2

install:
 - git config --global core.autocrlf true
 - dotnet tool install --global dotnet-sonarscanner
 - dotnet tool install --global coverlet.console

before_script:
 - dotnet restore

script:
 - sonar-scanner begin /k:$SONARCLOUD_PROJECT /o:$SONARCLOUD_ORGANIZATION /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login=$SONARCLOUD_TOKEN /d:sonar.cs.opencover.reportsPaths="tests\MyExpenses.Core.Api.UnitTests\coverage.opencover.xml"
 - dotnet build || travis_terminate 1;
 - dotnet test /p:Exclude="$TEST_EXCLUDE" /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
 - sonar-scanner end /d:sonar.login=$SONARCLOUD_TOKEN