version: "3"

services:
    myexpense-backend:
        build: .
        ports:
            - 5000:80
    mydb:
        image: images.artifactory.dunnhumby.com/postgres:latest
        #image: postgres:latest
        ports:
            - 5432:5432
